name: Traffic Logger

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

# Prevents multiple runs from overlapping and causing failures/emails
concurrency:
  group: traffic-logger
  cancel-in-progress: true

jobs:
  collect-traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run GitHub Repo Stats
        # Using @main to ensure we have the latest version of the action
        uses: jgehrcke/github-repo-stats@main
        with:
          ghtoken: ${{ secrets.TRAFFIC_TOKEN }}
          # The action uses 'databranch' to specify where to store the results
          databranch: gh-pages
